エラー時にメッセージを表示して終了させるabort関数を追加

diff --git a/generate-task-file b/generate-task-file
--- a/generate-task-file
+++ b/generate-task-file
@@ -41,13 +41,18 @@ done
 
 echo "${ask_issue_url}"
 
+abort () {
+  echo "$@" 1>&2
+  exit 1
+}
+
 while :
 do
   read -r issue_url
   if [[ -n "${issue_url}" ]]; then
     file_name="${issue_number}${task_name}.md"
     file_body=$(get_task_file_body)
-    echo "${file_body}" > "${task_dir_path}/${file_name}"
+    echo "${file_body}" > "${task_dir_path}/${file_name}" || abort 'ファイルの生成に失敗しました'
     echo "${file_name}でファイルを作成しました"
     break
   else
